### ISSUE TITLE
Cant delete pages

### ISSUE THREAD

**Issue by tshrinivasan** [alexz-enwp/wikitools#39]
When tried to use delete() method on a wiki page,

page.delete(pagename, reason="spam")
getting the following error.

  File "delete-pages.py", line 118, in <module>
    delete_page(page_name)
  File "delete-pages.py", line 101, in delete_page
    page.delete(pagename, reason = "spam")
TypeError: delete() got multiple values for keyword argument 'reason'

I tried giving various values for reason including True and False.

Getting same error.

Please guide me on how to delete the pages.

Thanks.

**Comment by tshrinivasan** [comment]
It was my mistake.

Have to use as

page.delete( reason = "spam")

It is working now.

**Comment by mzmcbride** [comment]
I'm glad you figured it out! :-)

If you think that the wikitools documentation can be improved, please submit a pull request.
